# STANDARD VALUES FOR THE PROGRAM

## COLOR THRESHOLDING
### IMAGES ARE IN GOOD CONDITION
GOOD_CONDITION = 1

### BLUE MARKERS COLORS STANDARD
#### LOWER LIMITS
BLUE_MARKER_LR = 0
BLUE_MARKER_LG = 0
BLUE_MARKER_LB = 120

#### UPPER LIMITS
BLUE_MARKER_UR = 140
BLUE_MARKER_UG = 140
BLUE_MARKER_UB = 255

### BROWN MARKERS COLORS STANDARD
#### LOWER LIMITS
BROWN_MARKER_LR = 0
BROWN_MARKER_LG = 0
BROWN_MARKER_LB = 0

#### UPPER LIMITS
BROWN_MARKER_UR = 255
BROWN_MARKER_UG = 255
BROWN_MARKER_UB = 110

## EDGE DETECTION METHOD
EDGE_DETECTION_TYPE = 1
EDGE_CANNY_LOWER = 75
EDGE_CANNY_UPPER = 100

## PERIMETER 
PERIMETER_MIN = 0
PERIMETER_MAX = 100

## CIRCULARITY
MIN_CIRCULARITY = 0.05
